# Generated by Django 4.0.4 on 2022-05-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='imag',
        ),
    ]
